// Generates a workbook that exercises EVERY exposed feature of the binding, so you
// can open it in Excel and eyeball the output. This file is intended to stay in
// sync with the public API (see CLAUDE.md "Keep the docs in sync").
//
//   npm run example          # writes examples/showcase.xlsx
//   npm run example -- path/to/out.xlsx
//
// Unlike the tests, this does NOT delete the file.

import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
import { dirname, resolve, join } from 'node:path'
import { writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { labelPng } from './png.mjs'

const require = createRequire(import.meta.url)
const {
  Workbook,
  Format,
  FormatAlign,
  FormatBorder,
  FormatPattern,
  FormatUnderline,
  Image,
  Chart,
  ChartType,
  ChartLegendPosition,
  Table,
  TableFunction,
  TableStyle,
  ConditionalFormatCell,
  ConditionalFormatCellRuleType,
  ConditionalFormatFormula,
  ConditionalFormat2ColorScale,
  ConditionalFormat3ColorScale,
  ConditionalFormatDataBar,
  DataValidation,
  DataValidationRuleType,
  DataValidationErrorStyle,
  Note,
  DocProperties,
} = require('../index.js')

const here = dirname(fileURLToPath(import.meta.url))
const outPath = resolve(process.argv[2] ?? join(here, 'showcase.xlsx'))

const wb = new Workbook()

// --- Workbook.setProperties / DocProperties (every setter) ------------------
wb.setProperties(
  new DocProperties()
    .setTitle('xlsxwriter-node showcase')
    .setSubject('Feature coverage')
    .setAuthor('xlsxwriter-node')
    .setManager('The Manager')
    .setCompany('Example Co.')
    .setCategory('Examples')
    .setKeywords('xlsx, napi, rust')
    .setComment('Generated by examples/showcase.mjs')
    .setStatus('Final')
    .setHyperlinkBase('https://example.com/')
    .setCustomProperty('Department', 'Engineering'),
)

// ===========================================================================
// Sheet 1 — cell writes + every Format setter
// ===========================================================================
const fmt = wb.addWorksheet('Writes & Formats')
fmt.setColumnWidth(0, 26)
fmt.setColumnWidth(1, 22)

// Generic write (dispatches on JS type) + the typed writers.
fmt.write(0, 0, 'string via write()')
fmt.write(0, 1, 123.45)
fmt.write(1, 0, 'boolean via write()')
fmt.write(1, 1, true)
fmt.writeString(2, 0, 'writeString')
fmt.writeNumber(2, 1, 42)
fmt.writeBoolean(3, 1, false)
fmt.writeString(3, 0, 'writeBoolean ->')
fmt.writeFormula(4, 1, '=B3 + 100') // boolean false coerces to 0 -> 100
fmt.writeString(4, 0, 'writeFormula ->')
fmt.writeDatetime(5, 1, new Date('2026-06-23T09:30:00Z'))
fmt.writeString(5, 0, 'writeDatetime ->')
fmt.writeUrl(6, 1, 'https://github.com/jmcnamara/rust_xlsxwriter')
fmt.writeString(6, 0, 'writeUrl ->')

// Every Format setter, spread across a few cells.
const f1 = new Format()
  .setBold()
  .setItalic()
  .setUnderline(FormatUnderline.Double)
  .setFontStrikethrough()
  .setFontName('Georgia')
  .setFontSize(13)
  .setFontColor(0xc00000)
  .setAlign(FormatAlign.Center)
fmt.writeWithFormat(8, 0, 'font styling', f1)

const f2 = new Format()
  .setNumFormat('$#,##0.00')
  .setBackgroundColor(0xfff2cc)
  .setPattern(FormatPattern.Solid)
  .setBorder(FormatBorder.Double)
fmt.writeWithFormat(8, 1, 1234.5, f2)

const f3 = new Format()
  .setForegroundColor(0x4472c4)
  .setPattern(FormatPattern.LightGrid)
  .setBorder(FormatBorder.Thin)
fmt.writeWithFormat(9, 0, 'pattern fill', f3)

const f4 = new Format()
  .setTextWrap()
  .setAlign(FormatAlign.VerticalCenter)
  .setIndent(2)
  .setRotation(30)
fmt.setRowHeight(9, 48)
fmt.writeWithFormat(9, 1, 'wrapped, indented & rotated text', f4)

// ===========================================================================
// Sheet 2 — every conditional-format type (and all their setters)
// ===========================================================================
const cf = wb.addWorksheet('Conditional')
const grid = [
  [10, 55, 90],
  [20, 45, 80],
  [70, 35, 15],
  [60, 25, 5],
]
grid.forEach((row, r) => row.forEach((v, c) => cf.write(r, c, v)))
cf.write(6, 0, -10)
cf.write(7, 0, 40)
cf.write(8, 0, -30)
cf.write(9, 0, 90)

const matchFmt = new Format().setBackgroundColor(0xc6efce).setFontColor(0x006100)

// Cell rule (uses setRule, setFormat, setMultiRange, setStopIfTrue).
cf.addConditionalFormatCell(
  0,
  0,
  3,
  0,
  new ConditionalFormatCell()
    .setRule(ConditionalFormatCellRuleType.Between, 15, 65)
    .setFormat(matchFmt)
    .setMultiRange('A1:A4 C1:C4')
    .setStopIfTrue(true),
)

// Formula rule (setRule, setFormat, setMultiRange, setStopIfTrue).
cf.addConditionalFormatFormula(
  0,
  1,
  3,
  1,
  new ConditionalFormatFormula()
    .setRule('=B1>50')
    .setFormat(new Format().setBackgroundColor(0xffc7ce))
    .setMultiRange('B1:B4')
    .setStopIfTrue(false),
)

// 2-color scale (setMinimumColor, setMaximumColor, setMultiRange).
cf.addConditionalFormat2ColorScale(
  0,
  2,
  3,
  2,
  new ConditionalFormat2ColorScale()
    .setMinimumColor(0xffffff)
    .setMaximumColor(0x63be7b)
    .setMultiRange('C1:C4'),
)

// 3-color scale (setMinimumColor, setMidpointColor, setMaximumColor, setMultiRange).
cf.addConditionalFormat3ColorScale(
  6,
  0,
  9,
  0,
  new ConditionalFormat3ColorScale()
    .setMinimumColor(0xf8696b)
    .setMidpointColor(0xffeb84)
    .setMaximumColor(0x63be7b)
    .setMultiRange('A7:A10'),
)

// Data bar (every setter).
cf.addConditionalFormatDataBar(
  6,
  2,
  9,
  2,
  new ConditionalFormatDataBar()
    .setFillColor(0x638ec6)
    .setBorderColor(0x244062)
    .setNegativeFillColor(0xff0000)
    .setSolidFill(true)
    .setBorderOff(false)
    .setMultiRange('C7:C10'),
)
// Give the data bar some values to render.
cf.write(6, 2, 30)
cf.write(7, 2, -20)
cf.write(8, 2, 60)
cf.write(9, 2, -40)

// ===========================================================================
// Sheet 3 — every DataValidation allow* rule + message configuration
// ===========================================================================
const dv = wb.addWorksheet('Validation')
dv.setColumnWidth(0, 30)
dv.setColumnWidth(1, 18)
const dvLabels = [
  'Whole number 1..100',
  'Decimal > 0',
  'Text length <= 10',
  'List (Yes/No/Maybe)',
  'List from formula',
  'Custom (ISNUMBER)',
  'Any value (+ messages)',
]
dvLabels.forEach((label, i) => dv.write(i, 0, label))
// Source values for the formula-based list.
dv.write(0, 3, 'Low')
dv.write(1, 3, 'Med')
dv.write(2, 3, 'High')

dv.addDataValidation(0, 1, 0, 1, new DataValidation().allowWholeNumber(DataValidationRuleType.Between, 1, 100))
dv.addDataValidation(1, 1, 1, 1, new DataValidation().allowDecimalNumber(DataValidationRuleType.GreaterThan, 0))
dv.addDataValidation(2, 1, 2, 1, new DataValidation().allowTextLength(DataValidationRuleType.LessThanOrEqualTo, 10))
dv.addDataValidation(
  3,
  1,
  3,
  1,
  new DataValidation().allowList(['Yes', 'No', 'Maybe']).setShowDropdown(true),
)
dv.addDataValidation(4, 1, 4, 1, new DataValidation().allowListFormula('=$D$1:$D$3'))
dv.addDataValidation(5, 1, 5, 1, new DataValidation().allowCustom('=ISNUMBER(B6)'))
dv.addDataValidation(
  6,
  1,
  6,
  1,
  new DataValidation()
    .allowAnyValue()
    .setIgnoreBlank(true)
    .setShowInputMessage(true)
    .setShowErrorMessage(true)
    .setInputTitle('Heads up')
    .setInputMessage('Type anything here')
    .setErrorTitle('Nope')
    .setErrorMessage('That is not allowed')
    .setErrorStyle(DataValidationErrorStyle.Warning)
    .setMultiRange('B7:C7'),
)

// ===========================================================================
// Sheet 4 — Table (every setter) + Charts (every method)
// ===========================================================================
const data = wb.addWorksheet('Table & Chart')
const headers = ['Quarter', 'Sales', 'Costs']
const series = [
  ['Q1', 100, 60],
  ['Q2', 140, 80],
  ['Q3', 180, 90],
  ['Q4', 220, 110],
]
headers.forEach((h, c) => data.write(0, c, h))
series.forEach((row, i) => row.forEach((v, c) => data.write(i + 1, c, v)))

const table = new Table()
  .setName('SalesTable')
  .setStyle(TableStyle.Medium9)
  .setColumns([
    { header: 'Quarter', totalLabel: 'Total' },
    { header: 'Sales', totalFunction: TableFunction.Sum },
    { header: 'Costs', totalFunction: TableFunction.Average },
  ])
  .setHeaderRow(true)
  .setTotalRow(true)
  .setBandedRows(true)
  .setBandedColumns(false)
  .setFirstColumn(true)
  .setLastColumn(false)
  .setAutofilter(true)
  .setAltText('Quarterly sales table')
data.addTable(0, 0, 5, 2, table) // rows 0..5 = header + 4 data + totals

// Chart 1: column chart with a positioned legend (covers setLegendPosition).
const chart1 = new Chart(ChartType.Column)
chart1
  .addSeries({ name: 'Sales', categories: "'Table & Chart'!$A$2:$A$5", values: "'Table & Chart'!$B$2:$B$5" })
  .addSeries({ name: 'Costs', categories: "'Table & Chart'!$A$2:$A$5", values: "'Table & Chart'!$C$2:$C$5" })
  .setTitle('Sales vs Costs')
  .setXAxisName('Quarter')
  .setYAxisName('Amount')
  .setLegendPosition(ChartLegendPosition.Bottom)
  .setStyle(12)
data.insertChart(8, 0, chart1)

// Chart 2: line chart with the legend hidden (covers setLegendHidden).
const chart2 = new Chart(ChartType.Line)
chart2
  .addSeries({ name: 'Sales', values: "'Table & Chart'!$B$2:$B$5" })
  .setTitle('Sales trend')
  .setLegendHidden()
  .setStyle(2)
data.insertChart(8, 8, chart2)

// ===========================================================================
// Sheet 5 — Images (fromPath + fromBuffer, scaling, alt text)
// ===========================================================================
const pics = wb.addWorksheet('Images')

// A real PNG generated on the fly: blue background, white "FROM BUFFER" text.
const bufferPng = labelPng('FROM BUFFER', { bg: [31, 78, 120], fg: [255, 255, 255] })
pics.write(0, 0, 'fromBuffer + scale + alt text:')
pics.insertImage(
  1,
  0,
  Image.fromBuffer(bufferPng).setScaleWidth(1).setScaleHeight(1).setAltText('Blue label image (from buffer)'),
)

// Another generated PNG (green bg), written to a temp file to demonstrate fromPath.
const pathPng = labelPng('FROM PATH', { bg: [0, 128, 80], fg: [255, 255, 255] })
const tmpPng = join(tmpdir(), 'xlsxwriter-node-showcase.png')
writeFileSync(tmpPng, pathPng)
pics.write(8, 0, 'fromPath + scale (0.75x):')
pics.insertImage(9, 0, Image.fromPath(tmpPng).setScaleWidth(0.75).setScaleHeight(0.75))

// ===========================================================================
// Sheet 6 — Cell note (every Note setter)
// ===========================================================================
const notes = wb.addWorksheet('Notes')
notes.setColumnWidth(0, 28)
notes.write(0, 0, 'Hover the next cell for a note ->')
notes.insertNote(
  0,
  1,
  new Note('Net of returns and discounts.')
    .setAuthor('Finance')
    .addAuthorPrefix(true)
    .setWidth(220)
    .setHeight(100)
    .setVisible(true)
    .setBackgroundColor(0xffffcc)
    .setFontName('Tahoma')
    .setFontSize(10)
    .setFormat(new Format().setBold())
    .setAltText('Finance note'),
)

// ===========================================================================
// Sheet 7 — Print / page setup (landscape) + autofilter
// ===========================================================================
const print = wb.addWorksheet('Print')
const colHeaders = ['Name', 'Team', 'Score']
colHeaders.forEach((h, c) => print.writeWithFormat(0, c, h, new Format().setBold()))
const people = [
  ['Ada', 'A', 91],
  ['Linus', 'B', 88],
  ['Grace', 'A', 95],
  ['Dennis', 'B', 80],
]
people.forEach((row, i) => row.forEach((v, c) => print.write(i + 1, c, v)))
print.autofilter(0, 0, 4, 2)

print.setLandscape()
print.setPaperSize(9) // A4
print.setZoom(125)
print.setMargins(0.7, 0.7, 0.75, 0.75, 0.3, 0.3)
print.setHeader('&CScores')
print.setFooter('&LShowcase&RPage &P of &N')
print.setPrintGridlines(true)
print.setScreenGridlines(true)
print.setPrintFitToPages(1, 1)
print.setPrintArea(0, 0, 4, 2)
print.setRepeatRows(0, 0)
print.setRepeatColumns(0, 0)

// ===========================================================================
// Sheet 8 — Layout (portrait, RTL, tab color, merge, freeze, row/col formats)
// ===========================================================================
const layout = wb.addWorksheet('LayoutTmp')
layout.setName('Layout') // rename via setName
layout.setPortrait()
layout.setRightToLeft(true)
layout.setTabColor(0x00b050)
layout.setScreenGridlines(false)
layout.setZoom(80)

const banner = new Format().setBold().setAlign(FormatAlign.Center).setBackgroundColor(0xdeebf7).setPattern(FormatPattern.Solid)
layout.mergeRange(0, 0, 0, 3, 'Merged banner', banner)
layout.setFreezePanes(1, 0)

layout.setColumnFormat(1, new Format().setNumFormat('0.00%'))
layout.setRowFormat(2, new Format().setItalic())
layout.write(2, 1, 0.4215) // shows as 42.15% via the column format
layout.write(2, 0, 'row is italic ->')

// ===========================================================================
// Sheet 9 — Hidden worksheet
// ===========================================================================
const hidden = wb.addWorksheet('Hidden')
hidden.write(0, 0, 'You can unhide me from the sheet tabs.')
hidden.setHidden(true)

// --- Save -------------------------------------------------------------------
wb.save(outPath)
console.log(`Wrote ${outPath} — open it in Excel to verify.`)

// --- Workbook.saveToBuffer (separate workbook, to avoid re-finalizing) ------
const memWb = new Workbook()
memWb.addWorksheet('Buffer').write(0, 0, 'saved to a Buffer')
const buf = memWb.saveToBuffer()
console.log(`saveToBuffer() returned a ${buf.length}-byte Buffer.`)
